# generate_temporal_encoding_table.py
# Full SM table: climate-adaptive temporal encoding ablation.
#
# Structure (Option A):
#   Primary rows  = test year (2021–2025)
#   Secondary     = model
#   Tertiary      = method (Baseline / T3S / T3S+TPE)
#   Columns       = OA, mIoU, ECE, NLL
#
# OA, GIoU, mIoU, mF1 are computed from the confusion matrix pkl (71x71, bg at 0),
# restricted to the 65 agricultural classes. ECE and NLL are from test_metrics.json.
# A missing confusion matrix pkl is a hard error — never fall back to JSON.
#
# Usage:
#   python scripts/tables/generate_temporal_encoding_table.py

import sys, json
import numpy as np
from pathlib import Path

ROOT    = Path(__file__).parents[2]
STORAGE = ROOT / "storage"
sys.path.insert(0, str(ROOT / "code" / "analysis"))
from eval_utils import get_ag_indices, crop_metrics_from_cm, load_cm

SPLITS     = ["S1", "S2", "S3", "S4", "S5"]
TEST_YEARS = {"S1": 2021, "S2": 2022, "S3": 2023, "S4": 2024, "S5": 2025}

MODELS = [
    ("U-TAE", [
        ("Baseline",   "utae_cloudsub"),
        ("$T^{3}S$",        "utae_gddsub"),
        ("$T^{3}S$ + TPE",  "utae_gddsub_gddpe"),
    ]),
    ("TSViT", [
        ("Baseline",   "tsvit_cloudsub"),
        ("$T^{3}S$",        "tsvit_gddsub"),
        ("$T^{3}S$ + TPE",  "tsvit_gddsub_gddpe"),
    ]),
    ("Galileo-nano (FT)", [
        ("Baseline",   "galileo_nano_cloudsub"),
        ("$T^{3}S$",        "galileo_nano_gddsub"),
        # T3S + TPE not applicable: fixed pretrained month-based PE
    ]),
]

# (key, display_header, precision, scale, higher_is_better)
# OA/GIoU/mIoU/mF1 come from the ag-restricted confusion matrix.
# ECE/NLL come from test_metrics.json (scale: ECE stored as fraction, multiply ×100).
COLUMNS = [
    ("oa",       "OA (\\%)",   1, 1.0,   True),
    ("miou",     "mIoU (\\%)", 1, 1.0,   True),
    ("mf1",      "mF1 (\\%)",  1, 1.0,   True),
    ("test_ECE", "ECE (\\%)",  2, 100.0, False),
    ("test_NLL", "NLL",        2, 1.0,   False),
]

OUTPUTS = [
    "results/tables/tab_temporal_encoding_full_body.tex",
    "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/tab_temporal_encoding_full_body.tex",
]

OUTPUTS_SUMMARY = [
    "results/tables/tab_temporal_encoding_body.tex",
    "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/tab_temporal_encoding_body.tex",
]

_AG_IDX, _NAG_IDX = get_ag_indices()


def load_metrics(folder):
    """
    Return dict of metrics for one split folder, or None if json missing.
    OA, GIoU, mIoU, mF1 from ag-restricted confusion matrix pkl.
    ECE and NLL from test_metrics.json.
    Raises FileNotFoundError if confusion matrix pkl is missing.
    """
    json_path = STORAGE / folder / "test_metrics.json"
    if not json_path.exists():
        return None
    cm = load_cm(STORAGE, folder)
    oa, giou, miou, mf1 = crop_metrics_from_cm(cm, _AG_IDX)
    with open(json_path) as f:
        j = json.load(f)
    return {
        "oa":       oa,
        "giou":     giou,
        "miou":     miou,
        "mf1":      mf1,
        "test_ECE": j["test_ECE"],
        "test_NLL": j["test_NLL"],
    }


def fmt(v, prec):
    return f"{v:.{prec}f}"


def bold(cell):
    return f"\\textbf{{{cell}}}"


def generate_body():
    ncols = len(COLUMNS)
    cmidrule = f"\\cmidrule(l){{2-{3 + ncols}}}"

    # Pre-load all data
    data = []
    for _, methods in MODELS:
        model_data = []
        for _, prefix in methods:
            split_data = {}
            for sp in SPLITS:
                if prefix is None:
                    split_data[sp] = None
                else:
                    split_data[sp] = load_metrics(f"{prefix}_{sp}")
            model_data.append(split_data)
        data.append(model_data)

    col_headers = " & ".join(h for _, h, _, _, _ in COLUMNS)
    lines = [
        "% auto-generated by generate_temporal_encoding_table.py — do not edit manually",
        f"% Year & Model & Method & {col_headers}",
        "% TODO: add mF1 (\\%) once conf_mat.pkl is available for all variants",
    ]

    for split in SPLITS:
        year = TEST_YEARS[split]

        for m_idx, (model_name, methods) in enumerate(MODELS):
            for mth_idx, (method_name, prefix) in enumerate(methods):
                m = data[m_idx][mth_idx][split]

                year_cell  = str(year) if (m_idx == 0 and mth_idx == 0) else ""
                model_cell = model_name if mth_idx == 0 else ""

                if prefix is None:
                    metric_cells = ["n/a"] * ncols
                elif m is None:
                    metric_cells = ["---"] * ncols
                else:
                    metric_cells = []
                    for key, _, prec, scale, _ in COLUMNS:
                        raw = m.get(key)
                        metric_cells.append(fmt(raw * scale, prec) if raw is not None else "---")

                row = " & ".join([year_cell, model_cell, method_name] + metric_cells)
                lines.append(row + " \\\\")

            if m_idx < len(MODELS) - 1:
                lines.append(cmidrule)

        # bold best per column within each year-model block
        # (post-process: re-scan the last 3*n_models rows and bold)
        lines.append("\\midrule")

    # ── Mean row ──────────────────────────────────────────────────────────────
    lines.append("\\midrule")
    for m_idx, (model_name, methods) in enumerate(MODELS):
        for mth_idx, (method_name, prefix) in enumerate(methods):
            mean_label = "Mean" if (m_idx == 0 and mth_idx == 0) else ""
            model_cell = model_name if mth_idx == 0 else ""

            if prefix is None:
                metric_cells = ["n/a"] * ncols
            else:
                n_avail = sum(1 for sp in SPLITS if data[m_idx][mth_idx][sp] is not None)
                if n_avail == 0:
                    metric_cells = ["---"] * ncols
                else:
                    metric_cells = []
                    star = "$^{\\star}$" if n_avail < len(SPLITS) else ""
                    for col_idx, (key, _, prec, scale, _) in enumerate(COLUMNS):
                        vals = [data[m_idx][mth_idx][sp][key] * scale
                                for sp in SPLITS
                                if data[m_idx][mth_idx][sp] is not None
                                and data[m_idx][mth_idx][sp].get(key) is not None]
                        if vals:
                            metric_cells.append(fmt(float(np.mean(vals)), prec) + star)
                        else:
                            metric_cells.append("---")

            row = " & ".join([mean_label, model_cell, method_name] + metric_cells)
            lines.append(row + " \\\\")

        if m_idx < len(MODELS) - 1:
            lines.append(cmidrule)

    if lines[-1].endswith(" \\\\"):
        lines[-1] = lines[-1][:-3]
    return "\n".join(lines).rstrip("\n")


def generate_summary_body():
    """Compact main-paper table: one row per model, columns = Baseline / T3S / T3S+TPE mIoU."""
    MIOU_KEY, MIOU_PREC, MIOU_SCALE = "miou", 1, 1.0

    # Pre-load all data (same structure as generate_body)
    data = []
    for _, methods in MODELS:
        model_data = []
        for _, prefix in methods:
            split_data = {}
            for sp in SPLITS:
                if prefix is None:
                    split_data[sp] = None
                else:
                    split_data[sp] = load_metrics(f"{prefix}_{sp}")
            model_data.append(split_data)
        data.append(model_data)

    # Compute per-model, per-method mean mIoU
    means = []  # means[m_idx][mth_idx] = (value_str, is_partial, is_na)
    for m_idx, (_, methods) in enumerate(MODELS):
        row = []
        for mth_idx, (_, prefix) in enumerate(methods):
            if prefix is None:
                row.append(("n/a", False, True))
                continue
            avail = [data[m_idx][mth_idx][sp] for sp in SPLITS
                     if data[m_idx][mth_idx][sp] is not None]
            if not avail:
                row.append(("---", False, False))
                continue
            vals = [m[MIOU_KEY] * MIOU_SCALE for m in avail if m.get(MIOU_KEY) is not None]
            partial = len(avail) < len(SPLITS)
            row.append((fmt(float(np.mean(vals)), MIOU_PREC), partial, False))
        means.append(row)

    # Determine max number of method columns across all models
    max_methods = max(len(methods) for _, methods in MODELS)

    # Bold best numeric value per row
    lines = ["% auto-generated by generate_temporal_encoding_table.py — do not edit manually"]
    for m_idx, (model_name, _) in enumerate(MODELS):
        numeric = [(mth_idx, float(v)) for mth_idx, (v, _, na) in enumerate(means[m_idx])
                   if not na and v not in ("---",)]
        best_val = max(v for _, v in numeric) if numeric else None
        cells = [model_name]
        for mth_idx, (v, partial, na) in enumerate(means[m_idx]):
            star = "$^\\star$" if partial else ""
            if na or v == "---":
                cells.append(v + star)
            elif best_val is not None and float(v) == best_val:
                cells.append(f"\\textbf{{{v}}}{star}")
            else:
                cells.append(v + star)
        # Pad missing method columns with --- (e.g. Galileo T3S+TPE not applicable)
        while len(cells) - 1 < max_methods:
            cells.append("---")
        lines.append(" & ".join(cells) + " \\\\")

    if lines[-1].endswith(" \\\\"):
        lines[-1] = lines[-1][:-3]
    return "\n".join(lines)


def main():
    body = generate_body()
    for output in OUTPUTS:
        out_path = ROOT / output
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            f.write(body)
        print(f"Written: {out_path}")

    summary = generate_summary_body()
    for output in OUTPUTS_SUMMARY:
        out_path = ROOT / output
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            f.write(summary)
        print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
