# generate_summary_table.py
# Benchmark summary table for SwissCrop25 (paper body).
#
# Structure:
#   Split (test year) as group header, one sub-row per model within each split.
#   Double rule at the bottom, followed by Mean ± Std sub-rows per model.
#
# Cols : OA (%) | GIoU (%) | mIoU (%) | mF1 (%) | ECE (%) | NLL
# Best value per column (within each split block) is bolded.
#
# OA, GIoU, mIoU, mF1 are computed from the confusion matrix pkl (71x71, bg at 0),
# restricted to the 65 agricultural classes (ag submatrix).
# ECE and NLL are read from test_metrics.json (calibration metrics not in conf mat).
# A missing confusion matrix pkl is a hard error — never fall back to JSON.
#
# Usage:
#   python scripts/tables/generate_summary_table.py

import sys
import json
import numpy as np
from pathlib import Path

ROOT        = Path(__file__).parents[2]
STORAGE     = ROOT / "storage"
sys.path.insert(0, str(ROOT / "code" / "analysis"))
from ag_classes import get_ag_indices, crop_metrics_from_cm, load_cm

SPLITS = ["S1", "S2", "S3", "S4", "S5"]

# LOYO test year for each split (from train_*.py _ablation_splits definition)
TEST_YEARS = {"S5": 2025, "S4": 2024, "S3": 2023, "S2": 2022, "S1": 2021}

# ── Model registry ────────────────────────────────────────────────────────────
# (display_name, folder_prefix)  — folder = prefix + "_S{n}"
MODELS = [
    ("U-TAE",                 "utae_gddsub_gddpe"),
    ("TSViT",                 "tsvit_gddsub_gddpe"),
    ("Galileo-nano (FT)",     "galileo_nano_gddsub"),
    ("Galileo-nano (frozen)", "galileo_nano_frozen_gddsub"),
    ("Galileo-base (frozen)", "galileo_base_frozen_gddsub"),
]

# ── Column definitions ────────────────────────────────────────────────────────
# (key, display_header, precision, higher_is_better)
# key is either a test_metrics.json key or a special computed key
COLUMNS = [
    ("oa",       "OA (\\%)",   1, True),
    ("giou",     "GIoU (\\%)", 1, True),
    ("miou",     "mIoU (\\%)", 1, True),
    ("mf1",      "mF1 (\\%)",  1, True),
    ("test_ECE", "ECE (\\%)",  2, False),
    ("test_NLL", "NLL",        2, False),
]

OUTPUTS = [
    "results/tables/benchmark_summary_body.tex",
    "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/benchmark_summary_body.tex",
]

# Main-paper table: 3 fine-tuned models only, with temporal encoding labels.
MODELS_MAIN = [
    ("U-TAE",            "utae_gddsub_gddpe"),
    ("TSViT",            "tsvit_gddsub_gddpe"),
    ("Galileo-nano (FT)", "galileo_nano_gddsub"),
]

OUTPUTS_MAIN = [
    "results/tables/benchmark_summary_main_body.tex",
    "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/benchmark_summary_main_body.tex",
]


# ── Metric loading ─────────────────────────────────────────────────────────────

_AG_IDX, _NAG_IDX = get_ag_indices()  # 1-based, loaded once


def load_split_metrics(folder):
    """
    Load metrics for one split folder. Returns dict or None if data missing.
    OA, GIoU, mIoU, mF1 are computed from the ag-restricted confusion matrix.
    ECE and NLL are read from test_metrics.json.
    Raises FileNotFoundError if the confusion matrix pkl is missing.
    """
    json_path = STORAGE / folder / "test_metrics.json"
    if not json_path.exists():
        return None

    cm = load_cm(STORAGE, folder)
    oa, giou, miou, mf1 = crop_metrics_from_cm(cm, _AG_IDX)

    with open(json_path) as f:
        j = json.load(f)

    return {
        "oa":       oa,
        "giou":     giou,
        "miou":     miou,
        "mf1":      mf1,
        "test_ECE": j["test_ECE"] * 100,
        "test_NLL": j["test_NLL"],
    }


# ── Formatting ────────────────────────────────────────────────────────────────

def fmt(v, precision):
    return f"{v:.{precision}f}"


def fmt_mean_sd(vals, precision):
    arr = np.array(vals, dtype=float)
    mean = arr.mean()
    if len(arr) > 1:
        sd = arr.std(ddof=1)
        return mean, sd, f"{mean:.{precision}f} $\\pm$ {sd:.{precision}f}"
    else:
        return mean, float("nan"), f"{mean:.{precision}f}$^\\star$"


def bold_best(val_str, best_str, cell_str):
    if val_str == best_str:
        return f"\\textbf{{{cell_str}}}"
    return cell_str


# ── Table generation ──────────────────────────────────────────────────────────

def generate_body(models_override=None):
    models = models_override if models_override is not None else MODELS
    # data[split][model_name] = metrics dict or None
    data = {}
    for split in SPLITS:
        data[split] = {}
        for name, prefix in models:
            data[split][name] = load_split_metrics(f"{prefix}_{split}")

    lines = ["% auto-generated by generate_summary_table.py — do not edit manually"]
    lines.append("% Split & Model & " + " & ".join(c[1] for c in COLUMNS))

    for s_idx, split in enumerate(SPLITS):
        if s_idx > 0:
            lines.append("\\midrule")

        avail = [(name, data[split][name]) for name, _ in models if data[split][name] is not None]
        best_in_split = {}
        for key, _, prec, higher in COLUMNS:
            vals = [fmt(data[split][name][key], prec) for name, _ in models
                    if data[split][name] is not None and data[split][name].get(key) is not None]
            if vals:
                best_in_split[key] = max(vals, key=float) if higher else min(vals, key=float)

        for m_idx, (name, prefix) in enumerate(models):
            m = data[split][name]
            split_label = str(TEST_YEARS[split]) if m_idx == 0 else ""
            if m is None:
                cells = [split_label, name] + ["---"] * len(COLUMNS)
            else:
                cells = [split_label, name]
                for key, _, prec, higher in COLUMNS:
                    raw = m.get(key)
                    if raw is None:
                        cells.append("---")
                    else:
                        v_str = fmt(raw, prec)
                        cell = bold_best(v_str, best_in_split.get(key, ""), v_str)
                        cells.append(cell)
            lines.append(" & ".join(cells) + r" \\")

    # ── Mean ± Std summary block ──────────────────────────────────────────────
    lines.append("\\midrule")
    lines.append("\\midrule")

    model_summaries = []
    for name, prefix in models:
        per_col = {key: [data[sp][name][key] for sp in SPLITS
                         if data[sp][name] is not None and data[sp][name].get(key) is not None]
                   for key, _, _, _ in COLUMNS}
        model_summaries.append((name, per_col))

    best_mean = {}
    for key, _, prec, higher in COLUMNS:
        means = [fmt(float(np.mean(pc[key])), prec) if pc[key] else None
                 for _, pc in model_summaries]
        valid = [v for v in means if v is not None]
        if valid:
            best_mean[key] = max(valid, key=float) if higher else min(valid, key=float)

    for m_idx, (name, per_col) in enumerate(model_summaries):
        mean_label = "Mean $\\pm$ Std" if m_idx == 0 else ""
        cells = [mean_label, name]
        for key, _, prec, higher in COLUMNS:
            vals = per_col[key]
            if not vals:
                cells.append("---")
                continue
            mean, sd, cell_str = fmt_mean_sd(vals, prec)
            mean_str = fmt(mean, prec)
            if mean_str == best_mean.get(key, ""):
                if np.isnan(sd):
                    cell_str = f"\\textbf{{{mean_str}}}$^\\star$"
                else:
                    cell_str = f"\\textbf{{{mean_str}}} $\\pm$ {sd:.{prec}f}"
            cells.append(cell_str)
        lines.append(" & ".join(cells) + r" \\")

    if lines[-1].endswith(r" \\"):
        lines[-1] = lines[-1][:-3]
    return "\n".join(lines).rstrip("\n")


def main():
    body = generate_body()
    for output in OUTPUTS:
        out_path = ROOT / output
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            f.write(body)
        print(f"Written: {out_path}")

    body_main = generate_body(models_override=MODELS_MAIN)
    for output in OUTPUTS_MAIN:
        out_path = ROOT / output
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            f.write(body_main)
        print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
