# generate_mask_table.py
# Binary agricultural mask evaluation for SwissCrop25.
#
# Remaps the 70-class conf_mat into agricultural vs non-agricultural using
# Crop_Label_lv3 from SwissCrop25.xlsx:
#   Agricultural : Arable Land, Permanent, Grassland  (classes 1-62, 69)
#   Non-agricultural: Forest, Water, Built-up, Unproductive Area, Wetland (classes 59,60,64-68,70)
#   Background (class 0, ignore_index) is excluded from evaluation.
#
# Outputs:
#   LaTeX table: Precision, Recall, F1, IoU(ag) per model, averaged over splits.
#
# Usage:
#   python scripts/analysis/generate_mask_table.py

import sys
import pickle
import numpy as np
from pathlib import Path

ROOT    = Path(__file__).parents[2]
sys.path.insert(0, str(ROOT / "code" / "analysis"))
from eval_utils import get_ag_indices

STORAGE = ROOT / "storage"

SPLITS = ["S5", "S4", "S3", "S2", "S1"]

MODELS = [
    ("U-TAE",        "utae_gddsub_gddpe",        "test_metrics.pkl"),
    ("TSViT",        "tsvit_gddsub_gddpe",   "test_metrics.pkl"),
    ("Galileo-nano", "galileo_nano_gddsub",        "conf_mat.pkl"),
]

MODELS_FULL = MODELS + [
    ("Galileo-nano (frozen)", "galileo_nano_frozen_gddsub", "conf_mat.pkl"),
    ("Galileo-base (frozen)", "galileo_base_frozen_gddsub", "conf_mat.pkl"),
]

OUTPUTS_MAIN = [
    ROOT / "results/tables/tab_mask_body.tex",
    ROOT / "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/tab_mask_body.tex",
]

OUTPUTS_FULL = [
    ROOT / "results/tables/tab_mask_full_body.tex",
    ROOT / "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/tab_mask_full_body.tex",
]

# SM baseline table: DL models + baselines, S2-S5 only (S1=test2021 baseline not computed)
MODELS_BASELINE = [
    ("U-TAE",             "utae_gddsub_gddpe",             "test_metrics.pkl"),
    ("TSViT",             "tsvit_gddsub_gddpe", "test_metrics.pkl"),
    ("Galileo-nano (FT)", "galileo_nano_gddsub",           "conf_mat.pkl"),
    ("Previous-year",     "prev_year_baseline",            "conf_mat.pkl"),
    ("Majority vote",     "majority_baseline",             "conf_mat.pkl"),
]
SPLITS_BASELINE = ["S2", "S3", "S4", "S5"]
OUTPUTS_BASELINE = [
    ROOT / "results/tables/tab_mask_baseline_body.tex",
    ROOT / "Lauber_2026_SwissCrop_ECCV26_TerraBytes/tables/tab_mask_baseline_body.tex",
]


# ── Binary metrics ────────────────────────────────────────────────────────────

def binary_metrics(cm, ag_idx, nag_idx):
    """Aggregate conf_mat into 2×2 and return precision, recall, F1, IoU(ag)."""
    tp = cm[np.ix_(ag_idx,  ag_idx)].sum()
    fn = cm[np.ix_(ag_idx,  nag_idx)].sum()
    fp = cm[np.ix_(nag_idx, ag_idx)].sum()
    tn = cm[np.ix_(nag_idx, nag_idx)].sum()   # noqa: F841 (for reference)
    eps = 1e-10
    prec = tp / (tp + fp + eps)
    rec  = tp / (tp + fn + eps)
    f1   = 2 * prec * rec / (prec + rec + eps)
    iou  = tp / (tp + fp + fn + eps)
    return prec * 100, rec * 100, f1 * 100, iou * 100


# ── Collect ───────────────────────────────────────────────────────────────────

def collect(ag_idx, nag_idx, models, splits=None):
    splits = splits or SPLITS
    results = {name: {"prec": [], "rec": [], "f1": [], "iou": []}
               for name, _, __ in models}

    for split in splits:
        for name, prefix, fname in models:
            path = STORAGE / f"{prefix}_{split}" / fname
            if not path.exists():
                continue
            cm = pickle.load(open(path, "rb")).astype(np.float64)
            prec, rec, f1, iou = binary_metrics(cm, ag_idx, nag_idx)
            results[name]["prec"].append(prec)
            results[name]["rec"].append(rec)
            results[name]["f1"].append(f1)
            results[name]["iou"].append(iou)

    return results


# ── LaTeX table ───────────────────────────────────────────────────────────────

ALL_COLS  = [("prec", "Precision (\\%)"), ("rec", "Recall (\\%)"),
             ("f1",   "F1 (\\%)"),        ("iou", "IoU$_{\\mathrm{ag}}$ (\\%)")]
MAIN_COLS = [("iou", "IoU$_{\\mathrm{ag}}$ (\\%)")]


def make_table(results, cols, models):
    best = {}
    for key, _ in cols:
        vals = [np.mean(results[name][key]) for name, _, __ in models
                if results[name][key]]
        best[key] = max(vals) if vals else None

    lines = ["% auto-generated by generate_mask_table.py — do not edit manually"]

    for name, _, __ in models:
        r = results[name]
        if not r["f1"]:
            cells = [name] + ["---"] * len(cols)
        else:
            cells = [name]
            for key, _ in cols:
                mean = np.mean(r[key])
                cell = f"{mean:.1f}"
                if best[key] is not None and abs(mean - best[key]) < 0.05:
                    cell = f"\\textbf{{{cell}}}"
                cells.append(cell)
        lines.append(" & ".join(cells) + r" \\")

    if lines[-1].endswith(r" \\"):
        lines[-1] = lines[-1][:-3]
    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    ag_idx, nag_idx = get_ag_indices()
    print(f"Agricultural classes  ({len(ag_idx)}): {ag_idx}")
    print(f"Non-agricultural classes ({len(nag_idx)}): {nag_idx}")

    results_main = collect(ag_idx, nag_idx, MODELS)
    results_full = collect(ag_idx, nag_idx, MODELS_FULL)

    for path in OUTPUTS_MAIN:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(make_table(results_main, MAIN_COLS, MODELS))
        print(f"Written: {path}")

    for path in OUTPUTS_FULL:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(make_table(results_full, ALL_COLS, MODELS_FULL))
        print(f"Written: {path}")

    results_baseline = collect(ag_idx, nag_idx, MODELS_BASELINE, splits=SPLITS_BASELINE)
    for path in OUTPUTS_BASELINE:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(make_table(results_baseline, ALL_COLS, MODELS_BASELINE))
        print(f"Written: {path}")

    print("\nBinary mask evaluation (mean over available splits):")
    print(f"{'Model':<28}  {'Prec':>6}  {'Rec':>6}  {'F1':>6}  {'IoU(ag)':>8}")
    for name, _, __ in MODELS_FULL:
        r = results_full[name]
        if not r["f1"]:
            print(f"{name:<28}  ---")
        else:
            print(f"{name:<28}  {np.mean(r['prec']):6.1f}  {np.mean(r['rec']):6.1f}"
                  f"  {np.mean(r['f1']):6.1f}  {np.mean(r['iou']):8.1f}  ({len(r['f1'])} splits)")


if __name__ == "__main__":
    main()
